version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: contenedor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: miapp
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: contenedor-mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  db_data: